### ISSUE TITLE
ZAP-01M: Fully Manipulative Vote

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#102]
## ZAP-01M: Fully Manipulative Vote Weight

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-major">Major</span> | [Zap.sol:L192](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/Zap.sol#L192) |

### Description:

The vote weight within the `vote` function entirely relies on the `balanceOf` measurement of the token that can be easily manipulated via flash loans.

### Example:

```solidity
function vote(uint256 _disputeId, bool _supportsDispute) external {
    uint256 voteWeight = token.balanceOf(msg.sender);
    zap.vote(_disputeId, _supportsDispute, voteWeight);
}
```

### Recommendation:

We advise the vote weight to be tracked historically similarly to the Compound implementation.

**Comment by jpkim921** [comment]
Instead of using _token.balanceOf(...)_ we can use _vault.userBalance(...)_ to use the staker's balance in the vault. Miner balances in the Vault are from when miners  first stake, when rewarded for mining and winning/losing a dispute. Miners do not have access to manipulate their balances within the vault.

**Comment by jpkim921** [comment]
Made the change to use vault balance instead of token balance.

Also asked for reviewers to double check that a user cannot just transfer somehow more zap into the vault. Pretty sure they can't.
