### ISSUE TITLE
Overly Centralized Control of Funds

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#109]
## ZMR-01M: Overly Centralized Control of Funds

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-medium">Medium</span> | [ZapMaster.sol:L75-L83](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/ZapMaster.sol#L75-L83) |

### Description:

All token funds held by the `ZapMaster` are in full custody of the contract's owner as they are able to transfer them to any address at will.

### Example:

```solidity
function sendBalToNewZM(address _newZapMaster) external onlyOwner {
    // require to be the owner of ZM to send to new ZM
    
    // total balance of current ZapMaster
    uint256 zapBalance = token.balanceOf(address(this));
    // approve entire balance
    token.approve(address(this), zapBalance);
    token.transferFrom(address(this), _newZapMaster, zapBalance);
}
```

### Recommendation:

We advise this portion to be potentially decied on by a DAO vote rather than a single-user action.

**Comment by jpkim921** [comment]
@kimanikelly replaced 'token.approve()` and `token.transferFrom(...)` with `token.transfer(...)` in PR #179.
But we should just removed this function `sendBalToNewZM`. Originally, it was created to transfer Zap balances between old and newly deployed ZM contracts. Deleting this function will not affect anything normal code operation.
