### ISSUE TITLE
Overwrittance of Existing Stake Withdrawal

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#115]
## ZSE-02M: Overwrittance of Existing Stake Withdrawal

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-minor">Minor</span> | [ZapStake.sol:L100-L115](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/libraries/ZapStake.sol#L100-L115) |

### Description:

The function overwrites the previous withdrawal request without properly managing the balance meant to be withdrawn.

### Example:

```solidity
function newStake(ZapStorage.ZapStorageStruct storage self, address staker) internal {
    // require(ZapTransfer.balanceOf(self,staker) >= self.uintVars[keccak256("stakeAmount")]);
    //Ensure they can only stake if they are not currrently staked or if their stake time frame has ended
    //and they are currently locked for witdhraw
    require(self.stakerDetails[staker].currentStatus == 0 || self.stakerDetails[staker].currentStatus == 2);
    self.uintVars[keccak256("stakerCount")] += 1;
    self.stakerDetails[staker] = ZapStorage.StakeInfo({
        currentStatus: 1,
        //this resets their stake start date to today
        startDate: now - (now % 86400)
    });
    // self.uintVars[keccak256("stakeAmount")]
    // ZapTransfer.updateBalanceAtNow(self.balances[staker], self.uintVars[keccak256("stakeAmount")]);

    emit NewStake(staker);
}
```

### Recommendation:

We advise this trait of the codebase to be carefully evaluated as desired.

**Comment by taejoonn** [comment]
This specific function is called from `depositStake()` line 90 of ZapStake.sol. The actual balance transfer is done in the upper layer at Zap.sol `depositStake()`, where it transfers funds and calls ZapStake's `depositStake()`.

This flow may have been overlooked during the audit and will close this issue.

**Comment by taejoonn** [comment]
To clarify the issue, if the user requested a withdraw, it is then possible for the user to deposit another stake before they withdraw. Which overwrites the previous requested withdraw.
