### ISSUE TITLE
Inexistent Subtraction of Staked Amount

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#116]
## ZTR-01M: Inexistent Subtraction of Staked Amount

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-major">Major</span> | [ZapTransfer.sol:L122](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/libraries/ZapTransfer.sol#L122) |

### Description:

The `allowedToTrade` function does not properly subtract the staked amount from the logic check of a transfer.

### Example:

```solidity
function allowedToTrade(
    ZapStorage.ZapStorageStruct storage self,
    address _user,
    uint256 _amount
) public view returns (bool) {
    if (self.stakerDetails[_user].currentStatus > 0) {
        //Removes the stakeAmount from balance if the _user is staked
        if (
            balanceOfAt(self, _user, block.number).sub(_amount) >= 0
        ) {
            return true;
        }
    } else if (balanceOfAt(self, _user, block.number).sub(_amount) >= 0) {
        return true;
    }
    return false;
}
```

### Recommendation:

We advise the amount to be properly subtracted from the user's balance to ensure they cannot transfer their staked balance.

**Comment by jpkim921** [comment]
Even though it's severity is major, I believe we can skip over this one. ZapTransfer was taken out of use. Maybe the better action for this is to remove all reference and instances of ZapTransfer - commented or otherwise out of the code base.
