### ISSUE TITLE
Comment Usage of `sha256`

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#126]
## MSE-01C: Comment Usage of `sha256`

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Code Style](/appendix/finding-types#code-style) | <span class="o-severity o-informational">Informational</span> | [MediaStorage.sol:L25](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/libraries/MediaStorage.sol#L25), [L29](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/libraries/MediaStorage.sol#L29) |

### Description:

The system states that it stores the `sha256` hashes of token content and metadata.

### Example:

```solidity
// Mapping from token id to sha256 hash of content
mapping(uint256 => bytes32) tokenContentHashes;

// Mapping from token id to sha256 hash of metadata
mapping(uint256 => bytes32) tokenMetadataHashes;
```

### Recommendation:

While this may be true due to the hashes being specified off-chain according to `ZapMedia`, we advise this to be validated as the `keccak256` instruction is different from the `sha256` instruction output and those two should not be confused.

**Comment by kimanikelly** [comment]
#156 Addresses this
