### ISSUE TITLE
Event Argument Optimization

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#127]
## OWB-01C: Event Argument Optimization

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [Ownable.sol:L20](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/libraries/Ownable.sol#L20) |

### Description:

The `OwnershipTransferred` redundantly reads the value of `owner` from storage.

### Example:

```solidity
function transferOwnership(address payable newOwner) public onlyOwner {
    require(newOwner != address(0));
    emit OwnershipTransferred(owner, newOwner);
    owner = newOwner;
}
```

### Recommendation:

We advise it to utilize `msg.sender` instead as it is guaranteed to equal `owner` due to the `onlyOwner` modifier.

**Comment by taejoonn** [comment]
Removing miner's Ownable.sol, unused.
