### ISSUE TITLE
Redundant Usage of SafeMath

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#141]
## ZMT-02C: Redundant Usage of SafeMath

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [ZapMarket.sol:L118](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L118), [L119](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L119), [L132](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L132), [L134](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L134), [L147](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L147), [L263](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L263), [L264](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L264), [L298](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L298), [L411-L414](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMarket.sol#L411-L414) |

### Description:

The contract system of the NFT component of Zap specifies Solidity version 0.8.4 and up which contain built-in safe arithmetic, causing the usage of SafeMath to incur extraneous gas.

### Example:

```solidity

t != 0 &&
nt ==
tShare(bidShares.creator, bidAmount)
.add(splitShare(bidShares.prevOwner, bidAmount))
.add(splitShare(bidShares.owner, bidAmount)));
```

### Recommendation:

We advise `SafeMath` to be omitted as a dependency from the system as it is redundant.

**Comment by Kaleb47** [comment]
I will work on this ticket
