### ISSUE TITLE
Data Location Optimization

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#145]
## ZMA-02C: Data Location Optimization

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Gas Optimization](/appendix/finding-types#gas-optimization) | <span class="o-severity o-informational">Informational</span> | [ZapMedia.sol:L140](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMedia.sol#L140), [L141](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMedia.sol#L141), [L144](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/ZapMedia.sol#L144) |

### Description:

The linked arguments are declared as `memory` in an `external` function.

### Example:

```solidity
function initialize(
    string memory name,
    string memory symbol,
    address marketContractAddr,
    bool permissive,
    string memory _collectionMetadata
) external override initializer {
```

### Recommendation:

We advise them to be set as `calldata` optimizing their gas cost.

**Comment by Kaleb47** [comment]
I can do this ticktet
