### ISSUE TITLE
Documentation: ZapVault

### ISSUE THREAD

**Issue by kimanikelly** [zapproject/hardhat-bsc#208]
## Summary 
ZapVault documentation is needed for testnet release 2.1.5. The frontend is using an implementation of ZapVault deployed from the ```creator-storage``` branch. This branch should be used as a reference no changes to the contract should be done to maintain the structure of the bytecode and ABI

## Branch For Documentation
```git checkout creator-storage```

### Functionality Files
```contracts/nft/ZapVault.sol```
```test/NftVaultTest.ts```

## Definition of Done
- Detailed information on how the NFT Vault handles transactions after ```acceptBid``` and ```endAuction``` is called

**Comment by jpkim921** [comment]
# ZapVault

Purpose of the ZapVault contract is to act as an escrow for tokens until bidding/selling of NFT(s) are accepted and finalized.

It extends several libraries and contracts which is listed below:

```solidity
import {SafeMathUpgradeable} from '@openzeppelin/contracts-upgradeable/utils/math/SafeMathUpgradeable.sol';
import {IERC20Upgradeable} from '@openzeppelin/contracts-upgradeable/token/ERC20/IERC20Upgradeable.sol';
import {SafeERC20Upgradeable} from '@openzeppelin/contracts-upgradeable/token/ERC20/utils/SafeERC20Upgradeable.sol';
import {Initializable} from '@openzeppelin/contracts/proxy/utils/Initializable.sol';
import {Decimal} from './Decimal.sol';
import {Ownable} from './access/Ownable.sol';
```


### FUNCTIONS

* initializeVault(token)
* vaultBalance() -> uint256
* withdraw(value)

Once ZapVault has been deployed, it is also used to deployed the ZapMarket contract. After deployment is complete, the ZapMarket contract would run a `setFee(fee)` function with a predetermined fee. In our case, it is set to 5 Zap tokens. 

In ZapMarket, when the `setBid(...)` function is called and the criteria matches the ask, `_finalizeNFTTransfer(...)` runs.

Similarly, `_finalizeNFTTransfer(...)` will run when the owner of the NFT accepts a bid `acceptBid(...)`.

In `_finalizeNFTTransfer(...)`, the current owner, previous owner (if any), creator, collaborators (if any) are paid their corresponding share of the token payment as well as the Zap Platform, whose fee was set above in `setFee(...)'. The NFT is transfer to the new owner and a new bid share is calculated.
