### ISSUE TITLE
Add OpenZeppelin `Upgradeable` to `ZapMaster`

### ISSUE THREAD

**Issue by taejoonn** [zapproject/hardhat-bsc#294]
### Summary
Add `Upgradeable` from OpenZeppelin to ZapMaster for forking functionality. This is in case `ZapStorage` will be modified in the future, then `ZapGetter` needs to reflect those changes, hence `ZapMaster`.

### Recommendation
https://docs.openzeppelin.com/contracts/4.x/upgradeable

### Definition of Done
Tests verifying passing vote for a ZapMaster fork and state-maintained on upgrade.

**Comment by taejoonn** [comment]
If this ZM is to be Upgradeable, we would be looking at a double proxy set up as ZM is already the proxy for pythia.

**Comment by kimanikelly** [comment]
When upgradeable contracts deploy there is a proxy contract and an implementation contract. If ZM is upgradeable we would be interacting with the proxy of that deployment.

**Comment by taejoonn** [comment]
ZM is a proxy in itself so if ZM is to become upgradeable, another proxy needs to be introduced. Hence a double proxy situation.

**Comment by taejoonn** [comment]
Closing this issue for now as I don't completely agree with having a double proxy.
