### ISSUE TITLE
Fetch Metadata Hash

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/hardhat-bsc#301]
### Description

we need a function to fetch the metadata of the NFT.

### Resource

Reference the Zora SDK

### Definition of Done

Test function in ganache, and make sure you are able to fetch the metadata.

**Comment by jpkim921** [comment]
Added the work(commit) to branch "issue30/fetchContentHash". #300 
Work flow is similar so it's easier to add and test at the same time.
