### ISSUE TITLE
setAuctionReservePrice

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/hardhat-bsc#320]
### Description

Write and test the setAuctionReservePrice.

```
 public async setAuctionReservePrice(
    auctionId: BigNumberish,
    reservePrice: BigNumberish
  ) {
    return this.auctionHouse.setAuctionReservePrice(auctionId, reservePrice)
  }
```

### Definition of Done

- [x] Write the function
- [x] Set a price for the Auction
- [x] Verify that the price has been set
- [x] Push and merge changes

**Comment by kimanikelly** [comment]
I will be working on this next
