### ISSUE TITLE
Snap Shot Governance Space

### ISSUE THREAD

**Issue by Kaleb47** [zapproject/hardhat-bsc#450]
### Description

Rather than writing a separate governance smart contract, or adding governance functionality to the zap token, users can vote on policies on snapshot.org.

### Definition of Done

- [x] [create an ENS web domain called zswap](https://docs.snapshot.org/spaces/before-creating-your-space)
- [x] [Set up the Zap space on Snap shot](https://docs.snapshot.org/spaces/create)
- [x] [Our space must be verified](https://docs.snapshot.org/spaces/get-verified).
- [x] [create a skin for our snapshot space](https://docs.snapshot.org/spaces/add-skin)

**Comment by pynchmeister** [comment]
This is completed. Addition tooling and proposals to roll out in tandem with Dex.

https://snapshot.org/#/zapgovernance.eth
