### ISSUE TITLE
Ownable contract compile warning

### ISSUE THREAD

**Issue by kimanikelly** [zapproject/hardhat-bsc#50]
## Summary
The public keyword on the Ownable.sol constructor is throwing a warning

## Cause of Warning
```contracts/nft/Ownable.sol```
<img width="969" alt="Screen Shot 2021-09-08 at 12 03 53 AM" src="https://user-images.githubusercontent.com/42893948/132444670-bb1c0263-601d-41c4-bcac-964c989883ee.png">

## Ownable.sol Warning
<img width="1105" alt="Screen Shot 2021-09-08 at 12 02 09 AM" src="https://user-images.githubusercontent.com/42893948/132444516-c3c3dbd5-9182-41db-b6b9-b80fe27c693f.png"><img width="1105" alt="Screen Shot 2021-09-08 at 12 02 09 AM" src="https://user-images.githubusercontent.com/42893948/132444516-c3c3dbd5-9182-41db-b6b9-b80fe27c693f.png">

## Definition of Done
- The public keyword is removed from the constructor
- Ownable.sol compiles without warnings

**Comment by acemasterjb** [comment]
This contract will also be upgradable, as a consequence this error will also be suppressed.
