### ISSUE TITLE
Deploy ZapToken.sol to Rinkeby

### ISSUE THREAD

**Issue by kimanikelly** [zapproject/hardhat-bsc#61]
## Summary
Related to #60 
ZapToken.sol needs to be deployed to be Rinkeby for testing with the NFT contracts

## Definition of Done
- ZapToken not ZapTokenBSC deployed to Rinkeby testnet

**Comment by logohere** [comment]
Who is working on this?

**Comment by kimanikelly** [comment]
Currently not assigned to anyone

**Comment by minciong** [comment]
ZapVault deployed to: 
0xCE5507b5beBdd5983bfCf05BfAD991c7eB5C5843
ZapMarket deployed to: 0xd023FD4E84B57aC2bC318A5234214bB5E6f4970D
ZapMedia deployed to: 0xfE896Fc2589C894b74Ee9823Fa1Cb2b082311403
AuctionHouse deployed to: 0xA6192853b42448B332E7157967F7B0aA8abF67EC

**Comment by kimanikelly** [comment]
ZapToken(ERC-20) & Faucet deployed to Rinkeby
```
Faucet Rinkeby 0xeed1fB6e2EAFA4ca88CF0C69F8fAd15CdA1dA240
ZapToken Rinkeby 0x5877451904f0484cc49DAFdfb8f9b33C8C31Ee2F
```
