### ISSUE TITLE
Inexistent Visibility Specifier

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#81]
## MGR-01S: Inexistent Visibility Specifier

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Code Style](/appendix/finding-types#code-style) | <span class="o-severity o-informational">Informational</span> | [MediaGetter.sol:L15](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/nft/MediaGetter.sol#L15) |

### Description:

The linked contract member has no visibility specifier explicitly set.

### Example:

```solidity
MediaStorage.Tokens tokens;
```

### Recommendation:

We advise one to be set so as otherwise the compiler assigns one automatically which can lead to compilation discrepancies between versions.

**Comment by kimanikelly** [comment]
#131  Addresses this
