### ISSUE TITLE
Pull-Over-Push Ownership Pattern

### ISSUE THREAD

**Issue by superposition** [zapproject/hardhat-bsc#99]
## OWB-01M: Pull-Over-Push Ownership Pattern

| Type | Severity | Location |
| ---- | -------- | -------- |
| [Logical Fault](/appendix/finding-types#logical-fault) | <span class="o-severity o-minor">Minor</span> | [Ownable.sol:L18-L22](https://github.com/zapproject/hardhat-bsc/blob/5712d542d9f6181f0a2e04a060ab8a1862cd4ede/contracts/zap-miner/libraries/Ownable.sol#L18-L22) |

### Description:

The codebase applies the push pattern within `transferOwnership`, assigning the `newOwner` without validating that they are aware of the ownership.

### Example:

```solidity
function transferOwnership(address payable newOwner) public onlyOwner {
    require(newOwner != address(0));
    emit OwnershipTransferred(owner, newOwner);
    owner = newOwner;
}
```

### Recommendation:

We advise the pull-over-push pattern to be conformed to here by instead proposing a new owner who consequently needs to accept ownership via a dedicated function, ensuring that they are aware of the ownership and are able to interact with the contract.

**Comment by taejoonn** [comment]
Removing the miner's Ownable.sol
